repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.88.4
  hooks:
    - id: terraform_fmt
      args:
        - --args=-write=true
    - id: terraform_tflint
    - id: terraform_docs
      args:
        - --args=--config=.terraform-docs.yml